---

- hosts: remote
  sudo: True
  roles:
    - role: bootstrap
    - role: security

- hosts: all
  sudo: True
  roles:
    - role: bootstrap
    - role: nginx
    - role: memcached
    # - role: mongodb
    # - role: nodejs
    # - role: ohmyzsh
    - role: python
    - role: postgresql
    # - role: rabbitmq
    # - role: rethink
    - role: supervisor
